/* Generated by Yosys 0.9 (git sha1 UNKNOWN, clang 12.0.0 -fPIC -Os) */

(* src = "sum_pipe.v:1" *)
module sum_pipe(clk, reset_L, dataA, dataB, sum30_dd, idx_dd);
  (* src = "sum_pipe.v:36" *)
  wire [3:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  (* src = "sum_pipe.v:7" *)
  (* unused_bits = "0" *)
  wire [1:0] acarreo;
  (* src = "sum_pipe.v:7" *)
  wire [1:0] acarreo_d;
  (* src = "sum_pipe.v:2" *)
  input clk;
  (* src = "sum_pipe.v:3" *)
  input [3:0] dataA;
  (* src = "sum_pipe.v:9" *)
  (* unused_bits = "0 1" *)
  wire [3:0] dataA_d;
  (* src = "sum_pipe.v:9" *)
  (* unused_bits = "0 1" *)
  wire [3:0] dataAant;
  (* src = "sum_pipe.v:3" *)
  input [3:0] dataB;
  (* src = "sum_pipe.v:9" *)
  (* unused_bits = "0 1" *)
  wire [3:0] dataB_d;
  (* src = "sum_pipe.v:9" *)
  (* unused_bits = "0 1" *)
  wire [3:0] dataBant;
  (* src = "sum_pipe.v:9" *)
  wire [3:0] idx;
  (* src = "sum_pipe.v:9" *)
  wire [3:0] idx_d;
  (* src = "sum_pipe.v:4" *)
  output [3:0] idx_dd;
  (* src = "sum_pipe.v:2" *)
  input reset_L;
  (* src = "sum_pipe.v:10" *)
  wire [1:0] sum10_d;
  (* src = "sum_pipe.v:9" *)
  wire [3:0] sum30_d;
  (* src = "sum_pipe.v:4" *)
  output [3:0] sum30_dd;
  NOT _18_ (
    .A(dataA_d[2]),
    .Y(_01_)
  );
  NOT _19_ (
    .A(dataB_d[2]),
    .Y(_02_)
  );
  NAND _20_ (
    .A(dataB[3]),
    .B(reset_L),
    .Y(_03_)
  );
  NOT _21_ (
    .A(_03_),
    .Y(dataBant[3])
  );
  NAND _22_ (
    .A(reset_L),
    .B(dataA[2]),
    .Y(_04_)
  );
  NOT _23_ (
    .A(_04_),
    .Y(dataAant[2])
  );
  NAND _24_ (
    .A(reset_L),
    .B(dataA[3]),
    .Y(_05_)
  );
  NOT _25_ (
    .A(_05_),
    .Y(dataAant[3])
  );
  NAND _26_ (
    .A(reset_L),
    .B(dataB[2]),
    .Y(_06_)
  );
  NOT _27_ (
    .A(_06_),
    .Y(dataBant[2])
  );
  NOR _28_ (
    .A(_01_),
    .B(_02_),
    .Y(_07_)
  );
  NAND _29_ (
    .A(dataA_d[2]),
    .B(dataB_d[2]),
    .Y(_08_)
  );
  NOR _30_ (
    .A(dataA_d[3]),
    .B(dataB_d[3]),
    .Y(_09_)
  );
  NOT _31_ (
    .A(_09_),
    .Y(_10_)
  );
  NAND _32_ (
    .A(dataA_d[3]),
    .B(dataB_d[3]),
    .Y(_11_)
  );
  NOT _33_ (
    .A(_11_),
    .Y(_12_)
  );
  NAND _34_ (
    .A(_10_),
    .B(_11_),
    .Y(_13_)
  );
  NOR _35_ (
    .A(_09_),
    .B(_12_),
    .Y(_14_)
  );
  NAND _36_ (
    .A(_08_),
    .B(_14_),
    .Y(_15_)
  );
  NAND _37_ (
    .A(_07_),
    .B(_13_),
    .Y(_16_)
  );
  NAND _38_ (
    .A(_15_),
    .B(_16_),
    .Y(_00_[3])
  );
  NOR _39_ (
    .A(dataA_d[2]),
    .B(dataB_d[2]),
    .Y(_17_)
  );
  NOR _40_ (
    .A(_07_),
    .B(_17_),
    .Y(_00_[2])
  );
  (* src = "sum_pipe.v:36" *)
  DFF _41_ (
    .C(clk),
    .D(_00_[2]),
    .Q(sum30_dd[2])
  );
  (* src = "sum_pipe.v:36" *)
  DFF _42_ (
    .C(clk),
    .D(_00_[3]),
    .Q(sum30_dd[3])
  );
  (* src = "sum_pipe.v:36" *)
  DFF _43_ (
    .C(clk),
    .D(dataAant[2]),
    .Q(dataA_d[2])
  );
  (* src = "sum_pipe.v:36" *)
  DFF _44_ (
    .C(clk),
    .D(dataAant[3]),
    .Q(dataA_d[3])
  );
  (* src = "sum_pipe.v:36" *)
  DFF _45_ (
    .C(clk),
    .D(dataBant[2]),
    .Q(dataB_d[2])
  );
  (* src = "sum_pipe.v:36" *)
  DFF _46_ (
    .C(clk),
    .D(dataBant[3]),
    .Q(dataB_d[3])
  );
  assign _00_[1:0] = 2'h0;
  assign acarreo[1] = 1'h0;
  assign acarreo_d = 2'h0;
  assign idx = 4'h0;
  assign idx_d = 4'h0;
  assign idx_dd = 4'h0;
  assign sum10_d = 2'h0;
  assign sum30_d = 4'h0;
  assign sum30_dd[1:0] = 2'h0;
endmodule

(* top =  1  *)
(* src = "sumador.v:3" *)
module sumador(clk, reset_L, dataA, dataB, sum30_dd, idx_dd);
  (* src = "sumador.v:4" *)
  input clk;
  (* src = "sumador.v:5" *)
  input [3:0] dataA;
  (* src = "sumador.v:5" *)
  input [3:0] dataB;
  (* src = "sumador.v:6" *)
  output [3:0] idx_dd;
  (* src = "sumador.v:4" *)
  input reset_L;
  (* src = "sumador.v:6" *)
  output [3:0] sum30_dd;
  (* module_not_derived = 32'd1 *)
  (* src = "sumador.v:9" *)
  sum_pipe sum (
    .clk(clk),
    .dataA(dataA),
    .dataB(dataB),
    .idx_dd(idx_dd),
    .reset_L(reset_L),
    .sum30_dd(sum30_dd)
  );
endmodule
